### ISSUE TITLE
Accessibility - First heading is not an H1

### ISSUE THREAD

**Issue by AmyJuneH** [badcamp/badcamp-2019#101]
To give your document a proper structure for assistive technologies, it is important to lay out your headings beginning with an h1. We found an h2 instead.
Relevant code:

h2 class="visually-hidden" id="block-mainnavigation-menu" style="font-size: 42.5px !important; line-height: 55.0001px !important;">Main navigation /h2

**Comment by mel-miller** [comment]
@AmyJuneH -- is this for the front page?

**Comment by AmyJuneH** [comment]
global @mel-miller

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3076621
