### ISSUE TITLE
Submit Drupal Planet RSS Feed to Drupal Planet

### ISSUE THREAD

**Issue by sean-e-dietrich** [badcamp/badcamp-2019#19]
So that Drupal Planet can see all of the blog posts that are placed on the site we must submit an RSS Feed to them for just articles with the Drupal Planet tag.

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/content/issues/3059486#comment-13138561

**Comment by JQTNguyen** [comment]
On June 4, I provided AmyJune with the tid and RSS Feed URL at https://2019.badcamp.org/taxonomy/term/5/feed, and Sean verified.

AmyJune submitted this on to Drupal.org the same day, and it got approved on June 8 at https://www.drupal.org/project/content/issues/3059486.

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3062368
