### ISSUE TITLE
Link identified only by color

### ISSUE THREAD

**Issue by AmyJuneH** [badcamp/badcamp-2019#2]
All pages:

	<a href="http://www.drupal.org/" style>Drupal</a>
	<a href="http://www.pantheon.io/" style>Pantheon</a>
 

1.4.1 Use of Color
Description of this issue:
It appears that color is the only distinguishing feature about links in blocks of text.

If links in blocks of text are identified only by color, the color contrast ratio between the link text and the surrounding text needs to be at least 3:1. This is not the case here.

Furthermore, for links identified only by color there should be additional visual cues when users point to the link with their mouse or move keyboard focus to the link. The additional visual cues could be underlining the link or making it bold.

This applies to links that are visually part of a block of text. Menu items etc. should not be considered here.

How to fix it:
Choose one of the following:

Make sure there are other visual indicators of links besides the color, such as underline or bold.

Or ensure that links have a contrast ratio of at least 3:1 with surrounding text, and provide additional visual cues when pointing with a mouse or moving keyboard focus to the link.

Please notice that the 3:1 color contrast ratio for links identified only by color should be measured text to text and not text to background.

**Comment by sean-e-dietrich** [comment]
Closing as old theme
