### ISSUE TITLE
Create Contact Form

### ISSUE THREAD

**Issue by torenware** [badcamp/badcamp-2019#23]
Stub; Link to the Contact Form from the FP, currently 404.

**Comment by sean-e-dietrich** [comment]
Fields should contain

* Name
* Email
* Subject
* Body

**Comment by torenware** [comment]
The contact-us form we get by default from webforms is not too bad, although it needs theming.  @mel-miller: are there standards for how we're doing forms.  I'm looking in the scss folder, but don't want to reinvent the wheel or any other neolithic tech here :-)

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3059195

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3059195
