### ISSUE TITLE
Submit Drupal Planet tag to Drupal Planet

### ISSUE THREAD

**Issue by sean-e-dietrich** [badcamp/badcamp-2019#26]
RSS Feed must be submitted to Drupal Planet

[Steps for setting up Drupal Planet](https://www.drupal.org/drupalorg/docs/content/planet-drupal)

**Comment by JQTNguyen** [comment]
This has been completed.

On June 4, I provided AmyJune with the tid and RSS Feed URL at https://2019.badcamp.org/taxonomy/term/5/feed, and Sean verified.

AmyJune submitted this on to Drupal.org the same day, and it got approved on June 8 at https://www.drupal.org/project/content/issues/3059486.

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3062368
