### ISSUE TITLE
No top-level heading on the page

### ISSUE THREAD

**Issue by AmyJuneH** [badcamp/badcamp-2019#3]
Pages have no H1

 1.3.1 Info and Relationships
Description of this issue:
A top level heading helps user agents such as screen readers and search engines to know the main topic of a page.
How to fix it:
Make sure your page has a top level heading (H1 or WAI-ARIA role="heading" aria-level="1") that matches the main topic of the page.

**Comment by sean-e-dietrich** [comment]
Closing as old theme
