### ISSUE TITLE
Get/create transparent logos for core-level sponsors

### ISSUE THREAD

**Issue by mel-miller** [badcamp/badcamp-2019#30]

**Comment by mel-miller** [comment]
![acquia-logo](https://user-images.githubusercontent.com/1753611/57201997-04815980-6f55-11e9-9986-25d5f61e18f2.png)
![pantheon-logo](https://user-images.githubusercontent.com/1753611/57201998-05b28680-6f55-11e9-9aa7-79b52d3a4a02.png)

**Comment by mel-miller** [comment]
Added to dev site.

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3068769
