### ISSUE TITLE
Set default user picture

### ISSUE THREAD

**Issue by mel-miller** [badcamp/badcamp-2019#37]

**Comment by mel-miller** [comment]
![badcamp-drop](https://user-images.githubusercontent.com/1753611/56618656-22a39d00-65d8-11e9-831a-5483ffadb40a.png)

**Comment by mel-miller** [comment]
Added to dev site.

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3062372
