### ISSUE TITLE
Theme Summit Pages

### ISSUE THREAD

**Issue by sean-e-dietrich** [badcamp/badcamp-2019#43]
All summit pages should be themed.

**Comment by mel-miller** [comment]
https://2018.badcamp.org/summits

**Comment by mel-miller** [comment]
@sean-e-dietrich — are you purposely waiting until later to add the remaining fields (time slot, room, etc...) since they will be reference fields?

**Comment by sean-e-dietrich** [comment]
@mel-miller yes because I'm not 100% sure what I'm doing for the schedule piece.

**Comment by mel-miller** [comment]
@sean-e-dietrich — no problem. I'm going to do a PR for the summits theme as it is now and can enhance later once we start with the schedule and sessions.

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3059193
