### ISSUE TITLE
Styles for Second-Level Menu Items for Mobile

### ISSUE THREAD

**Issue by mel-miller** [badcamp/badcamp-2019#50]
May consider changing foundation menu type for this. TBD.

**Comment by JQTNguyen** [comment]
At Medium Breakpoints, when the (Mobile) Menu is expanded, Menu Items appears to the Left in an Unhappy Way.

Steps to Reproduce:
1. Go to a Page that will produce Child Menu Items in the Main Menu (e.g.: https://2019.badcamp.org/sponsors).
2. Change the Browser Width to be below 1024px.
3. Hover over the Parent Menu Item (in the example above, hover over "Sponsors").

![Sponsors___Bay_Area_Drupal_Camp_-_2019_and_Fix_Menu_at_Medium_Breakpoints_·_Issue__64_·_badcamp_badcamp-2019](https://user-images.githubusercontent.com/3485338/59463344-a01aab00-8dda-11e9-8498-89aa0699288f.png)

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3070399
