### ISSUE TITLE
Social Media icons not displaying properly

### ISSUE THREAD

**Issue by mel-miller** [badcamp/badcamp-2019#61]
Haven't had a chance to investigate yet, but it may have something to do with mismatched or conflicting inclusion of fontawesome between module and theme. 

![Screen Shot 2019-05-12 at 6 19 59 PM](https://user-images.githubusercontent.com/1753611/57597129-f73f0e80-7502-11e9-8894-b1a2c8d86542.png)

**Comment by mel-miller** [comment]
This seems fine on the hosted dev site though. May end up closing this.

**Comment by sean-e-dietrich** [comment]
@mel-miller I commented out the version of FontAwesome being used in the stylesheet as that was causing issues. This should be all fixed now if you pull down.
