### ISSUE TITLE
Social media icons - Empty links

### ISSUE THREAD

**Issue by AmyJuneH** [badcamp/badcamp-2019#7]
Errors
Empty link

What It Means
A link contains no text.

Why It Matters
If a link contains no text, the function or purpose of the link will not be presented to the user. This can introduce confusion for keyboard and screen reader users.

How to Fix It
Remove the empty link or provide text within the link that describes the functionality and/or target of that link.
The Algorithm... in English
An anchor element has an href attribute, but contains no text (or only spaces) and no images with alternative text.

Standards and Guidelines
2.4.4 Link Purpose (In Context) (Level A)

**Comment by sean-e-dietrich** [comment]
Closing as old theme
