### ISSUE TITLE
Refactor how link styles are applied

### ISSUE THREAD

**Issue by mel-miller** [badcamp/badcamp-2019#72]
I found that they were originally applied globally to <a> tags. I've been removing them on a case-by-case basis, but they keep appearing in unexpected places. See article image in screenshot. SO, I'm going to refactor them to be opt-in instead opt-out per style. 

<img width="439" alt="Screen Shot 2019-06-13 at 4 30 10 PM" src="https://user-images.githubusercontent.com/1753611/59473833-f3035b00-8df8-11e9-8b06-378d3df35f82.png">

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3070393
