### ISSUE TITLE
Add Code of Conduct (and corresponding content) to site

### ISSUE THREAD

**Issue by mel-miller** [badcamp/badcamp-2019#74]
The Badcamp diversity and inclusion committee is working on drafting this and I will add it to the site as soon as possible.

**Comment by AmyJuneH** [comment]
https://2019.badcamp.org/badcamp-code-conduct
I added the Drupal CoC as a temporary page until one is drafted.

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3074008
