### ISSUE TITLE
Theme Job Board

### ISSUE THREAD

**Issue by JQTNguyen** [badcamp/badcamp-2019#88]
1. Create a Basic Page for the Job Board at /job-board.
2. Insert the "Job Postings - Master" View in the Components.
3. Theme this to be similar to the previous Job Board at https://2018.badcamp.org/job-board, and strip out the markup in the Teaser that is displayed in this listing.

---

Examples of Steps #1 and #2 can be found at https://2019.badcamp.org/job-board.

For Step #3, per Sean, we may be able to re-use the Template File for 2018.

**Comment by mel-miller** [comment]
4. theme job posting node display

**Comment by mel-miller** [comment]
Steps 3 and 4 are complete. Once this is pushed up to master steps 1 and 2 can be completed. Also step 2 should use the "listings" display. 

I can do this, but I'll be out of commission today (monday), so if you need it sooner, this is where we're at.

**Comment by mel-miller** [comment]
@JQTNguyen -- this is now complete. I used the page you already created and changed the view to the "listings" display. Closing.

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3074007
