### ISSUE TITLE
Admin menu looks a bit wonky (too big)

### ISSUE THREAD

**Issue by mel-miller** [badcamp/badcamp-2019#91]
I may have broken this with another update. I'll fix. 
![Screen Shot 2019-07-30 at 12 51 06 PM](https://user-images.githubusercontent.com/1753611/62160607-3b9fa680-b2c9-11e9-9255-417e8bd879c2.png)

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3074004
