### ISSUE TITLE
Fix line height and spacing on h1

### ISSUE THREAD

**Issue by mel-miller** [badcamp/badcamp-2019#96]
![Screen Shot 2019-08-06 at 12 20 43 PM](https://user-images.githubusercontent.com/1753611/62586233-91e48a80-b871-11e9-996a-3e773d73be05.png)

**Comment by mel-miller** [comment]
fixed via #97

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3075241#comment-13224012
